In [ ]:
import os
import json

# Step 1: Create the .kaggle directory
os.makedirs("/root/.kaggle", exist_ok=True)

# Step 2: Replace with your actual Kaggle username and token
kaggle_token = {
    "username": "soniana",  # ← replace this
    "key": "KGAT_2c587135e5c800b281d7f6049256e612"
}

# Step 3: Save kaggle.json to the correct location
with open("/root/.kaggle/kaggle.json", "w") as f:
    json.dump(kaggle_token, f)

# Step 4: Set permissions
!chmod 600 /root/.kaggle/kaggle.json

In [ ]:
!kaggle datasets list

ref                                                  title                                           size  lastUpdated                 downloadCount  voteCount  usabilityRating
---------------------------------------------------  ----------------------------------------  ----------  --------------------------  -------------  ---------  ---------------
neurocipher/heartdisease                             Heart Disease                                   3491  2025-12-11 15:29:14.327000           2114        204  1.0
ahmeduzaki/wind-and-solar-energy-production-dataset  Wind & Solar Energy Production Dataset        395372  2026-01-02 21:06:22.780000              0         35  1.0
kundanbedmutha/exam-score-prediction-dataset         Exam Score Prediction Dataset                 325454  2025-11-28 07:29:01.047000           5863        249  1.0
guriya79/heart-failure-prediction-dataset            Heart Failure Clinical Records Study            4067  2025-12-27 05:13:37.790000              0         28  1.0
neurocipher/student-performance                      Student Performance                            49705  2025-12-12 12:06:28.973000           1261        120  1.0
ishank2005/salary-csv                                Salary.csv                                       392  2025-12-29 15:48:58.240000              0         27  1.0
dansbecker/melbourne-housing-snapshot                Melbourne Housing Snapshot                    461423  2018-06-05 12:52:24.087000         200095       1722  0.7058824
datasnaek/youtube-new                                Trending YouTube Video Statistics          210575746  2019-06-03 00:56:47.177000         292850       5843  0.7941176
zynicide/wine-reviews                                Wine Reviews                                53336293  2017-11-27 17:08:04.700000         343808       3817  0.7941176
datasnaek/chess                                      Chess Game Dataset (Lichess)                 2903760  2017-09-04 03:09:09.453000          60913       1435  0.8235294
dansbecker/powerlifting-database                     powerlifting-database                        9277600  2019-04-30 21:07:41.560000          24255        352  0.5882353
residentmario/ramen-ratings                          Ramen Ratings                                  40762  2018-01-11 16:04:39.893000          54264        970  0.7058824
rtatman/188-million-us-wildfires                     1.88 Million US Wildfires                  176270559  2020-05-12 21:03:49.213000          41816       1408  0.8235294
nolanbconaway/pitchfork-data                         18,393 Pitchfork Reviews                    34891456  2017-01-13 04:18:10.113000          16956        444  0.7058824
nasa/kepler-exoplanet-search-results                 Kepler Exoplanet Search Results              1215549  2017-10-10 18:26:59.497000          21070        838  0.8235294
residentmario/things-on-reddit                       Things on Reddit                            16773230  2017-10-26 14:10:15.157000          14697        308  0.5882353
jpmiller/publicassistance                            US Public Food Assistance 1 - WIC             304041  2023-04-17 20:01:05.960000          24802        500  0.9411765
mohitsinghrajput1307/practice-dataset1               Customer Purchase Prediction Dataset             286  2026-01-02 13:05:59.963000              0         11  1.0
wardabilal/spotify-global-music-dataset-20092025     Spotify Global Music Dataset (2009–2025)     1289021  2025-11-11 09:43:05.933000          16387        475  1.0
suvidyasonawane/student-performance-dataset          Student Performance Dataset                    81679  2025-12-25 05:27:51.453000              0         48  1.0

In [ ]:
!kaggle datasets download -d mlg-ulb/creditcardfraud
!unzip creditcardfraud.zip

Dataset URL: https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud
License(s): DbCL-1.0
Downloading creditcardfraud.zip to /content
  0% 0.00/66.0M [00:00<?, ?B/s]
100% 66.0M/66.0M [00:00<00:00, 914MB/s]
Archive:  creditcardfraud.zip
  inflating: creditcard.csv

In [ ]:
import pandas as pd

df = pd.read_csv("creditcard.csv")
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [ ]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [ ]:
X = df.drop("Class", axis=1)
y = df["Class"]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [ ]:
from imblearn.over_sampling import SMOTE

sm = SMOTE(random_state=42)
X_train_res, y_train_res = sm.fit_resample(X_train, y_train)

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression


scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_res)
X_test_scaled = scaler.transform(X_test)

lr = LogisticRegression(max_iter=5000)
lr.fit(X_train_scaled, y_train_res)

LogisticRegression(max_iter=5000)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=12,
    random_state=42
)
rf.fit(X_train_res, y_train_res)

RandomForestClassifier(max_depth=12, n_estimators=200, random_state=42)

In [ ]:
from sklearn.metrics import classification_report, precision_score, recall_score

print("Logistic Regression Results:")
print(classification_report(y_test, lr.predict(X_test)))

print("\nRandom Forest Results:")
print(classification_report(y_test, rf.predict(X_test)))

Logistic Regression Results:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.02      0.02      0.02        98

    accuracy                           1.00     56962
   macro avg       0.51      0.51      0.51     56962
weighted avg       1.00      1.00      1.00     56962


Random Forest Results:

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.61      0.88      0.72        98

    accuracy                           1.00     56962
   macro avg       0.80      0.94      0.86     56962
weighted avg       1.00      1.00      1.00     56962

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_res)
X_test_scaled = scaler.transform(X_test)

In [ ]:
lr = LogisticRegression(max_iter=5000)

In [ ]:
lr = LogisticRegression(max_iter=5000, solver="saga")

In [ ]:
lr.fit(X_train_scaled, y_train_res)

LogisticRegression(max_iter=5000, solver='saga')

In [ ]:
from sklearn.metrics import classification_report, precision_score, recall_score

print("Logistic Regression Results:")
print(classification_report(y_test, lr.predict(X_test)))

Logistic Regression Results:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.01      0.01      0.01        98

    accuracy                           1.00     56962
   macro avg       0.51      0.50      0.50     56962
weighted avg       1.00      1.00      1.00     56962

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(

In [ ]:
lr_precision = precision_score(y_test, lr.predict(X_test))
lr_recall = recall_score(y_test, lr.predict(X_test))

rf_precision = precision_score(y_test, rf.predict(X_test))
rf_recall = recall_score(y_test, rf.predict(X_test))

print("Logistic Regression → Precision:", lr_precision, "Recall:", lr_recall)
print("Random Forest → Precision:", rf_precision, "Recall:", rf_recall)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(

Logistic Regression → Precision: 0.013157894736842105 Recall: 0.01020408163265306
Random Forest → Precision: 0.6099290780141844 Recall: 0.8775510204081632